import { readFileSync, writeFileSync } from "node:fs";
const m = await import("/dev-server/dist/server/_ssr/personalized-pdf.server-CG7-KXMW.mjs");
const fn = Object.values(m).find(v => typeof v === "function");
console.log("exports:", Object.keys(m));
// build a simple master pdf
const pl = await import("/dev-server/node_modules/pdf-lib/es/index.js");
const master = await pl.PDFDocument.create();
master.addPage([595,842]).drawText("MASTER COVER", {x:50,y:700,size:24});
const masterBytes = await master.save();
const out = await m.generatePersonalizedPdf({
  masterPdfBytes: masterBytes,
  fullName: "Burak Akçakanat",
  email: "burakakcakanat@gmail.com",
  dedicationBody: "Sevgili {{FULL_NAME}},\nbu nüsha sizin için imzalandı. Işığınız bol olsun.",
  footerTemplate: "Bu nüsha {{FULL_NAME}} ({{EMAIL}}) adına kişiselleştirilmiştir.",
  authorName: "Burak Akçakanat",
  signatureBytes: null,
  giftNote: null,
  buyerName: null,
  locale: "tr",
});
writeFileSync("/tmp/personalized.pdf", out);
console.log("generated bytes:", out.length);
