/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebinarlarRouteImport } from './routes/webinarlar'
import { Route as VideolarRouteImport } from './routes/videolar'
import { Route as SeanslarRouteImport } from './routes/seanslar'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as KitaplarRouteImport } from './routes/kitaplar'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkindaRouteImport } from './routes/hakkinda'
import { Route as EgitimRouteImport } from './routes/egitim'
import { Route as DegerlendirmeRouteImport } from './routes/degerlendirme'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DegerlendirmeMiniRouteImport } from './routes/degerlendirme_.mini'
import { Route as AuthenticatedHesabimRouteImport } from './routes/_authenticated/hesabim'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedRaporSessionIdRouteImport } from './routes/_authenticated/rapor.$sessionId'
import { Route as AuthenticatedDegerlendirmeTamRouteImport } from './routes/_authenticated/degerlendirme.tam'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const WebinarlarRoute = WebinarlarRouteImport.update({
  id: '/webinarlar',
  path: '/webinarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const VideolarRoute = VideolarRouteImport.update({
  id: '/videolar',
  path: '/videolar',
  getParentRoute: () => rootRouteImport,
} as any)
const SeanslarRoute = SeanslarRouteImport.update({
  id: '/seanslar',
  path: '/seanslar',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const KitaplarRoute = KitaplarRouteImport.update({
  id: '/kitaplar',
  path: '/kitaplar',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkindaRoute = HakkindaRouteImport.update({
  id: '/hakkinda',
  path: '/hakkinda',
  getParentRoute: () => rootRouteImport,
} as any)
const EgitimRoute = EgitimRouteImport.update({
  id: '/egitim',
  path: '/egitim',
  getParentRoute: () => rootRouteImport,
} as any)
const DegerlendirmeRoute = DegerlendirmeRouteImport.update({
  id: '/degerlendirme',
  path: '/degerlendirme',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DegerlendirmeMiniRoute = DegerlendirmeMiniRouteImport.update({
  id: '/degerlendirme_/mini',
  path: '/degerlendirme/mini',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHesabimRoute = AuthenticatedHesabimRouteImport.update({
  id: '/hesabim',
  path: '/hesabim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRaporSessionIdRoute =
  AuthenticatedRaporSessionIdRouteImport.update({
    id: '/rapor/$sessionId',
    path: '/rapor/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDegerlendirmeTamRoute =
  AuthenticatedDegerlendirmeTamRouteImport.update({
    id: '/degerlendirme/tam',
    path: '/degerlendirme/tam',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/degerlendirme': typeof DegerlendirmeRoute
  '/egitim': typeof EgitimRoute
  '/hakkinda': typeof HakkindaRoute
  '/iletisim': typeof IletisimRoute
  '/kitaplar': typeof KitaplarRoute
  '/mcp': typeof McpRoute
  '/seanslar': typeof SeanslarRoute
  '/videolar': typeof VideolarRoute
  '/webinarlar': typeof WebinarlarRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/hesabim': typeof AuthenticatedHesabimRoute
  '/degerlendirme/mini': typeof DegerlendirmeMiniRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/degerlendirme/tam': typeof AuthenticatedDegerlendirmeTamRoute
  '/rapor/$sessionId': typeof AuthenticatedRaporSessionIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/degerlendirme': typeof DegerlendirmeRoute
  '/egitim': typeof EgitimRoute
  '/hakkinda': typeof HakkindaRoute
  '/iletisim': typeof IletisimRoute
  '/kitaplar': typeof KitaplarRoute
  '/mcp': typeof McpRoute
  '/seanslar': typeof SeanslarRoute
  '/videolar': typeof VideolarRoute
  '/webinarlar': typeof WebinarlarRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/hesabim': typeof AuthenticatedHesabimRoute
  '/degerlendirme/mini': typeof DegerlendirmeMiniRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/degerlendirme/tam': typeof AuthenticatedDegerlendirmeTamRoute
  '/rapor/$sessionId': typeof AuthenticatedRaporSessionIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/degerlendirme': typeof DegerlendirmeRoute
  '/egitim': typeof EgitimRoute
  '/hakkinda': typeof HakkindaRoute
  '/iletisim': typeof IletisimRoute
  '/kitaplar': typeof KitaplarRoute
  '/mcp': typeof McpRoute
  '/seanslar': typeof SeanslarRoute
  '/videolar': typeof VideolarRoute
  '/webinarlar': typeof WebinarlarRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/hesabim': typeof AuthenticatedHesabimRoute
  '/degerlendirme_/mini': typeof DegerlendirmeMiniRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/degerlendirme/tam': typeof AuthenticatedDegerlendirmeTamRoute
  '/_authenticated/rapor/$sessionId': typeof AuthenticatedRaporSessionIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/degerlendirme'
    | '/egitim'
    | '/hakkinda'
    | '/iletisim'
    | '/kitaplar'
    | '/mcp'
    | '/seanslar'
    | '/videolar'
    | '/webinarlar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/hesabim'
    | '/degerlendirme/mini'
    | '/.mcp/invoke-tool/$tool'
    | '/degerlendirme/tam'
    | '/rapor/$sessionId'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/degerlendirme'
    | '/egitim'
    | '/hakkinda'
    | '/iletisim'
    | '/kitaplar'
    | '/mcp'
    | '/seanslar'
    | '/videolar'
    | '/webinarlar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/hesabim'
    | '/degerlendirme/mini'
    | '/.mcp/invoke-tool/$tool'
    | '/degerlendirme/tam'
    | '/rapor/$sessionId'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/degerlendirme'
    | '/egitim'
    | '/hakkinda'
    | '/iletisim'
    | '/kitaplar'
    | '/mcp'
    | '/seanslar'
    | '/videolar'
    | '/webinarlar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/hesabim'
    | '/degerlendirme_/mini'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/degerlendirme/tam'
    | '/_authenticated/rapor/$sessionId'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  DegerlendirmeRoute: typeof DegerlendirmeRoute
  EgitimRoute: typeof EgitimRoute
  HakkindaRoute: typeof HakkindaRoute
  IletisimRoute: typeof IletisimRoute
  KitaplarRoute: typeof KitaplarRoute
  McpRoute: typeof McpRoute
  SeanslarRoute: typeof SeanslarRoute
  VideolarRoute: typeof VideolarRoute
  WebinarlarRoute: typeof WebinarlarRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DegerlendirmeMiniRoute: typeof DegerlendirmeMiniRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webinarlar': {
      id: '/webinarlar'
      path: '/webinarlar'
      fullPath: '/webinarlar'
      preLoaderRoute: typeof WebinarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videolar': {
      id: '/videolar'
      path: '/videolar'
      fullPath: '/videolar'
      preLoaderRoute: typeof VideolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seanslar': {
      id: '/seanslar'
      path: '/seanslar'
      fullPath: '/seanslar'
      preLoaderRoute: typeof SeanslarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitaplar': {
      id: '/kitaplar'
      path: '/kitaplar'
      fullPath: '/kitaplar'
      preLoaderRoute: typeof KitaplarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkinda': {
      id: '/hakkinda'
      path: '/hakkinda'
      fullPath: '/hakkinda'
      preLoaderRoute: typeof HakkindaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egitim': {
      id: '/egitim'
      path: '/egitim'
      fullPath: '/egitim'
      preLoaderRoute: typeof EgitimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/degerlendirme': {
      id: '/degerlendirme'
      path: '/degerlendirme'
      fullPath: '/degerlendirme'
      preLoaderRoute: typeof DegerlendirmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/degerlendirme_/mini': {
      id: '/degerlendirme_/mini'
      path: '/degerlendirme/mini'
      fullPath: '/degerlendirme/mini'
      preLoaderRoute: typeof DegerlendirmeMiniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hesabim': {
      id: '/_authenticated/hesabim'
      path: '/hesabim'
      fullPath: '/hesabim'
      preLoaderRoute: typeof AuthenticatedHesabimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rapor/$sessionId': {
      id: '/_authenticated/rapor/$sessionId'
      path: '/rapor/$sessionId'
      fullPath: '/rapor/$sessionId'
      preLoaderRoute: typeof AuthenticatedRaporSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/degerlendirme/tam': {
      id: '/_authenticated/degerlendirme/tam'
      path: '/degerlendirme/tam'
      fullPath: '/degerlendirme/tam'
      preLoaderRoute: typeof AuthenticatedDegerlendirmeTamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHesabimRoute: typeof AuthenticatedHesabimRoute
  AuthenticatedDegerlendirmeTamRoute: typeof AuthenticatedDegerlendirmeTamRoute
  AuthenticatedRaporSessionIdRoute: typeof AuthenticatedRaporSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHesabimRoute: AuthenticatedHesabimRoute,
  AuthenticatedDegerlendirmeTamRoute: AuthenticatedDegerlendirmeTamRoute,
  AuthenticatedRaporSessionIdRoute: AuthenticatedRaporSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  DegerlendirmeRoute: DegerlendirmeRoute,
  EgitimRoute: EgitimRoute,
  HakkindaRoute: HakkindaRoute,
  IletisimRoute: IletisimRoute,
  KitaplarRoute: KitaplarRoute,
  McpRoute: McpRoute,
  SeanslarRoute: SeanslarRoute,
  VideolarRoute: VideolarRoute,
  WebinarlarRoute: WebinarlarRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DegerlendirmeMiniRoute: DegerlendirmeMiniRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
