/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KitaplarRouteImport } from './routes/kitaplar'
import { Route as DegerlendirmeRouteImport } from './routes/degerlendirme'
import { Route as IndexRouteImport } from './routes/index'

const KitaplarRoute = KitaplarRouteImport.update({
  id: '/kitaplar',
  path: '/kitaplar',
  getParentRoute: () => rootRouteImport,
} as any)
const DegerlendirmeRoute = DegerlendirmeRouteImport.update({
  id: '/degerlendirme',
  path: '/degerlendirme',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/degerlendirme': typeof DegerlendirmeRoute
  '/kitaplar': typeof KitaplarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/degerlendirme': typeof DegerlendirmeRoute
  '/kitaplar': typeof KitaplarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/degerlendirme': typeof DegerlendirmeRoute
  '/kitaplar': typeof KitaplarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/degerlendirme' | '/kitaplar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/degerlendirme' | '/kitaplar'
  id: '__root__' | '/' | '/degerlendirme' | '/kitaplar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DegerlendirmeRoute: typeof DegerlendirmeRoute
  KitaplarRoute: typeof KitaplarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kitaplar': {
      id: '/kitaplar'
      path: '/kitaplar'
      fullPath: '/kitaplar'
      preLoaderRoute: typeof KitaplarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/degerlendirme': {
      id: '/degerlendirme'
      path: '/degerlendirme'
      fullPath: '/degerlendirme'
      preLoaderRoute: typeof DegerlendirmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DegerlendirmeRoute: DegerlendirmeRoute,
  KitaplarRoute: KitaplarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
